name: "skip-push-on-pr"

description: "Skips a push event workflow run if it is predicated that a pull_request workflow run will occur."

inputs:
  GITHUB_TOKEN:
    description: "github authentication token secret"
    required: true

outputs:
  must-skip:
    description: "Indicates if a skip must happen"

runs:
  using: "node16"
  main: "main.js"
